# Generated by Django 3.2.5 on 2021-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inder_site', '0002_idea_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=1280, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='collaborator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='idea_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
    ]
