# Generated by Django 3.2.5 on 2021-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inder_site', '0004_auto_20210707_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_last_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=1280, null=True),
        ),
    ]
