# Generated by Django 3.2.5 on 2021-07-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inder_site', '0005_auto_20210707_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
